package com.birdcopy.BirdCopyApp.DataManager.ActiveDAO;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BE__RONG_USER.
 */
public class BE_RongUser {

    private Long id;
    /** Not-null value. */
    private String userid;
    private String name;
    private String portraitUri;

    public BE_RongUser() {
    }

    public BE_RongUser(Long id) {
        this.id = id;
    }

    public BE_RongUser(Long id, String userid, String name, String portraitUri) {
        this.id = id;
        this.userid = userid;
        this.name = name;
        this.portraitUri = portraitUri;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getUserid() {
        return userid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPortraitUri() {
        return portraitUri;
    }

    public void setPortraitUri(String portraitUri) {
        this.portraitUri = portraitUri;
    }

}
