package com.birdcopy.BirdCopyApp.DataManager.ActiveDAO;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table BE__TASK__WORD.
*/
public class BE_TASK_WORDDao extends AbstractDao<BE_TASK_WORD, Long> {

    public static final String TABLENAME = "BE__TASK__WORD";

    /**
     * Properties of entity BE_TASK_WORD.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property BEUSERID = new Property(1, String.class, "BEUSERID", false, "BEUSERID");
        public final static Property BEWORD = new Property(2, String.class, "BEWORD", false, "BEWORD");
        public final static Property BESENTENCEID = new Property(3, String.class, "BESENTENCEID", false, "BESENTENCEID");
        public final static Property BELESSONID = new Property(4, String.class, "BELESSONID", false, "BELESSONID");
        public final static Property BETIME = new Property(5, Integer.class, "BETIME", false, "BETIME");
    };


    public BE_TASK_WORDDao(DaoConfig config) {
        super(config);
    }
    
    public BE_TASK_WORDDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'BE__TASK__WORD' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'BEUSERID' TEXT NOT NULL ," + // 1: BEUSERID
                "'BEWORD' TEXT NOT NULL ," + // 2: BEWORD
                "'BESENTENCEID' TEXT," + // 3: BESENTENCEID
                "'BELESSONID' TEXT," + // 4: BELESSONID
                "'BETIME' INTEGER);"); // 5: BETIME
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'BE__TASK__WORD'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, BE_TASK_WORD entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getBEUSERID());
        stmt.bindString(3, entity.getBEWORD());
 
        String BESENTENCEID = entity.getBESENTENCEID();
        if (BESENTENCEID != null) {
            stmt.bindString(4, BESENTENCEID);
        }
 
        String BELESSONID = entity.getBELESSONID();
        if (BELESSONID != null) {
            stmt.bindString(5, BELESSONID);
        }
 
        Integer BETIME = entity.getBETIME();
        if (BETIME != null) {
            stmt.bindLong(6, BETIME);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public BE_TASK_WORD readEntity(Cursor cursor, int offset) {
        BE_TASK_WORD entity = new BE_TASK_WORD( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // BEUSERID
            cursor.getString(offset + 2), // BEWORD
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // BESENTENCEID
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // BELESSONID
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5) // BETIME
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, BE_TASK_WORD entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setBEUSERID(cursor.getString(offset + 1));
        entity.setBEWORD(cursor.getString(offset + 2));
        entity.setBESENTENCEID(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setBELESSONID(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setBETIME(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(BE_TASK_WORD entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(BE_TASK_WORD entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
