package com.birdcopy.BirdCopyApp.DataManager.ActiveDAO;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table BE__TASK__WORD.
 */
public class BE_TASK_WORD {

    private Long id;
    /** Not-null value. */
    private String BEUSERID;
    /** Not-null value. */
    private String BEWORD;
    private String BESENTENCEID;
    private String BELESSONID;
    private Integer BETIME;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public BE_TASK_WORD() {
    }

    public BE_TASK_WORD(Long id) {
        this.id = id;
    }

    public BE_TASK_WORD(Long id, String BEUSERID, String BEWORD, String BESENTENCEID, String BELESSONID, Integer BETIME) {
        this.id = id;
        this.BEUSERID = BEUSERID;
        this.BEWORD = BEWORD;
        this.BESENTENCEID = BESENTENCEID;
        this.BELESSONID = BELESSONID;
        this.BETIME = BETIME;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getBEUSERID() {
        return BEUSERID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBEUSERID(String BEUSERID) {
        this.BEUSERID = BEUSERID;
    }

    /** Not-null value. */
    public String getBEWORD() {
        return BEWORD;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBEWORD(String BEWORD) {
        this.BEWORD = BEWORD;
    }

    public String getBESENTENCEID() {
        return BESENTENCEID;
    }

    public void setBESENTENCEID(String BESENTENCEID) {
        this.BESENTENCEID = BESENTENCEID;
    }

    public String getBELESSONID() {
        return BELESSONID;
    }

    public void setBELESSONID(String BELESSONID) {
        this.BELESSONID = BELESSONID;
    }

    public Integer getBETIME() {
        return BETIME;
    }

    public void setBETIME(Integer BETIME) {
        this.BETIME = BETIME;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
