package com.birdcopy.BirdCopyApp.DataManager.ActiveDAO;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bE_PUB_LESSONDaoConfig;
    private final DaoConfig bE_LOCAl_LESSONDaoConfig;
    private final DaoConfig bE_STATISTICDaoConfig;
    private final DaoConfig bE_TOUCH_RECORDDaoConfig;
    private final DaoConfig bE_TASK_WORDDaoConfig;
    private final DaoConfig bE_RongUserDaoConfig;

    private final BE_PUB_LESSONDao bE_PUB_LESSONDao;
    private final BE_LOCAl_LESSONDao bE_LOCAl_LESSONDao;
    private final BE_STATISTICDao bE_STATISTICDao;
    private final BE_TOUCH_RECORDDao bE_TOUCH_RECORDDao;
    private final BE_TASK_WORDDao bE_TASK_WORDDao;
    private final BE_RongUserDao bE_RongUserDao;


    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bE_PUB_LESSONDaoConfig = daoConfigMap.get(BE_PUB_LESSONDao.class).clone();
        bE_PUB_LESSONDaoConfig.initIdentityScope(type);

        bE_LOCAl_LESSONDaoConfig = daoConfigMap.get(BE_LOCAl_LESSONDao.class).clone();
        bE_LOCAl_LESSONDaoConfig.initIdentityScope(type);

        bE_STATISTICDaoConfig = daoConfigMap.get(BE_STATISTICDao.class).clone();
        bE_STATISTICDaoConfig.initIdentityScope(type);

        bE_TOUCH_RECORDDaoConfig = daoConfigMap.get(BE_TOUCH_RECORDDao.class).clone();
        bE_TOUCH_RECORDDaoConfig.initIdentityScope(type);

        bE_TASK_WORDDaoConfig = daoConfigMap.get(BE_TASK_WORDDao.class).clone();
        bE_TASK_WORDDaoConfig.initIdentityScope(type);

        bE_RongUserDaoConfig = daoConfigMap.get(BE_RongUserDao.class).clone();
        bE_RongUserDaoConfig.initIdentityScope(type);


        bE_PUB_LESSONDao = new BE_PUB_LESSONDao(bE_PUB_LESSONDaoConfig, this);
        bE_LOCAl_LESSONDao = new BE_LOCAl_LESSONDao(bE_LOCAl_LESSONDaoConfig, this);
        bE_STATISTICDao = new BE_STATISTICDao(bE_STATISTICDaoConfig, this);
        bE_TOUCH_RECORDDao = new BE_TOUCH_RECORDDao(bE_TOUCH_RECORDDaoConfig, this);
        bE_TASK_WORDDao = new BE_TASK_WORDDao(bE_TASK_WORDDaoConfig, this);

        bE_RongUserDao = new BE_RongUserDao(bE_RongUserDaoConfig, this);

        registerDao(BE_PUB_LESSON.class, bE_PUB_LESSONDao);
        registerDao(BE_LOCAl_LESSON.class, bE_LOCAl_LESSONDao);
        registerDao(BE_STATISTIC.class, bE_STATISTICDao);
        registerDao(BE_TOUCH_RECORD.class, bE_TOUCH_RECORDDao);
        registerDao(BE_TASK_WORD.class, bE_TASK_WORDDao);

        registerDao(BE_RongUser.class, bE_RongUserDao);

    }
    
    public void clear() {
        bE_PUB_LESSONDaoConfig.getIdentityScope().clear();
        bE_LOCAl_LESSONDaoConfig.getIdentityScope().clear();
        bE_STATISTICDaoConfig.getIdentityScope().clear();
        bE_TOUCH_RECORDDaoConfig.getIdentityScope().clear();
        bE_TASK_WORDDaoConfig.getIdentityScope().clear();
        bE_RongUserDaoConfig.getIdentityScope().clear();
    }

    public BE_PUB_LESSONDao getBE_PUB_LESSONDao() {
        return bE_PUB_LESSONDao;
    }

    public BE_LOCAl_LESSONDao getBE_LOCAl_LESSONDao() {
        return bE_LOCAl_LESSONDao;
    }

    public BE_STATISTICDao getBE_STATISTICDao() {
        return bE_STATISTICDao;
    }

    public BE_TOUCH_RECORDDao getBE_TOUCH_RECORDDao() {
        return bE_TOUCH_RECORDDao;
    }

    public BE_TASK_WORDDao getBE_TASK_WORDDao() {
        return bE_TASK_WORDDao;
    }

    public BE_RongUserDao getBE_RongUserDao() {
        return bE_RongUserDao;
    }
}
