package com.birdcopy.BirdCopyApp.Component.ActiveDAO;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BE__DIC__PUB.
 */
public class BE_DIC_PUB {

    private Long id;
    /** Not-null value. */
    private String BEWORD;
    private Integer BEINDEX;
    private String BEENTRY;
    private String BETAG;

    public BE_DIC_PUB() {
    }

    public BE_DIC_PUB(Long id) {
        this.id = id;
    }

    public BE_DIC_PUB(Long id, String BEWORD, Integer BEINDEX, String BEENTRY, String BETAG) {
        this.id = id;
        this.BEWORD = BEWORD;
        this.BEINDEX = BEINDEX;
        this.BEENTRY = BEENTRY;
        this.BETAG = BETAG;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getBEWORD() {
        return BEWORD;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBEWORD(String BEWORD) {
        this.BEWORD = BEWORD;
    }

    public Integer getBEINDEX() {
        return BEINDEX;
    }

    public void setBEINDEX(Integer BEINDEX) {
        this.BEINDEX = BEINDEX;
    }

    public String getBEENTRY() {
        return BEENTRY;
    }

    public void setBEENTRY(String BEENTRY) {
        this.BEENTRY = BEENTRY;
    }

    public String getBETAG() {
        return BETAG;
    }

    public void setBETAG(String BETAG) {
        this.BETAG = BETAG;
    }

}
