package com.birdcopy.BirdCopyApp.Component.ActiveDAO;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table BE__LOCAL__LESSON.
 */
public class BE_LOCAl_LESSON {

    private Long id;
    /** Not-null value. */
    private String BEUSERID;
    /** Not-null value. */
    private String BELESSONID;
    private double BESTAMP;
    private String BELOCALCOVER;
    private Integer BETIME;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public BE_LOCAl_LESSON() {
    }

    public BE_LOCAl_LESSON(Long id) {
        this.id = id;
    }

    public BE_LOCAl_LESSON(Long id, String BEUSERID, String BELESSONID, double BESTAMP, String BELOCALCOVER, Integer BETIME) {
        this.id = id;
        this.BEUSERID = BEUSERID;
        this.BELESSONID = BELESSONID;
        this.BESTAMP = BESTAMP;
        this.BELOCALCOVER = BELOCALCOVER;
        this.BETIME = BETIME;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getBEUSERID() {
        return BEUSERID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBEUSERID(String BEUSERID) {
        this.BEUSERID = BEUSERID;
    }

    /** Not-null value. */
    public String getBELESSONID() {
        return BELESSONID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBELESSONID(String BELESSONID) {
        this.BELESSONID = BELESSONID;
    }

    public double getBESTAMP() {
        return BESTAMP;
    }

    public void setBESTAMP(double BESTAMP) {
        this.BESTAMP = BESTAMP;
    }

    public String getBELOCALCOVER() {
        return BELOCALCOVER;
    }

    public void setBELOCALCOVER(String BELOCALCOVER) {
        this.BELOCALCOVER = BELOCALCOVER;
    }

    public Integer getBETIME() {
        return BETIME;
    }

    public void setBETIME(Integer BETIME) {
        this.BETIME = BETIME;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
