package com.birdcopy.BirdCopyApp.Component.ActiveDAO;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import java.io.Serializable;

/**
 * Entity mapped to table BE__PUB__LESSON.
 */
public class BE_PUB_LESSON implements Serializable{

    private Long id;
    /** Not-null value. */
    private String BELESSONID;
    private String BETITLE;
    private String BEDESC;
    private String BEIMAGEURL;
    private String BECONTENTURL;
    private String BESUBURL;
    private Double BEDURATION;
    private Double BESTARTTIME;
    private Integer BELESSONS;
    private Double BEDLPERCENT;
    private Boolean BEDLSTATE;
    private Boolean BEOFFICIAL;
    private String BEPROURL;
    private String BELEVEL;
    private String BECONTENTTYPE;
    private String BEDOWNLOADTYPE;
    private String BETAG;
    private String BEWEBURL;
    private String BEISBN;
    private Integer BECoinPrice;
    private String BERELATIVEURL;
    private String localURLOfContent;
    private String localURLOfSub;
    private String localURLOfCover;
    private String localURLOfPro;
    private String localURLOfRelative;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public BE_PUB_LESSON() {
    }

    public BE_PUB_LESSON(Long id) {
        this.id = id;
    }

    public BE_PUB_LESSON(Long id, String BELESSONID, String BETITLE, String BEDESC, String BEIMAGEURL, String BECONTENTURL, String BESUBURL, Double BEDURATION, Double BESTARTTIME, Integer BELESSONS, Double BEDLPERCENT, Boolean BEDLSTATE, Boolean BEOFFICIAL, String BEPROURL, String BELEVEL, String BECONTENTTYPE, String BEDOWNLOADTYPE, String BETAG, String BEWEBURL, String BEISBN, Integer BECoinPrice, String BERELATIVEURL, String localURLOfContent, String localURLOfSub, String localURLOfCover, String localURLOfPro, String localURLOfRelative) {
        this.id = id;
        this.BELESSONID = BELESSONID;
        this.BETITLE = BETITLE;
        this.BEDESC = BEDESC;
        this.BEIMAGEURL = BEIMAGEURL;
        this.BECONTENTURL = BECONTENTURL;
        this.BESUBURL = BESUBURL;
        this.BEDURATION = BEDURATION;
        this.BESTARTTIME = BESTARTTIME;
        this.BELESSONS = BELESSONS;
        this.BEDLPERCENT = BEDLPERCENT;
        this.BEDLSTATE = BEDLSTATE;
        this.BEOFFICIAL = BEOFFICIAL;
        this.BEPROURL = BEPROURL;
        this.BELEVEL = BELEVEL;
        this.BECONTENTTYPE = BECONTENTTYPE;
        this.BEDOWNLOADTYPE = BEDOWNLOADTYPE;
        this.BETAG = BETAG;
        this.BEWEBURL = BEWEBURL;
        this.BEISBN = BEISBN;
        this.BECoinPrice = BECoinPrice;
        this.BERELATIVEURL = BERELATIVEURL;
        this.localURLOfContent = localURLOfContent;
        this.localURLOfSub = localURLOfSub;
        this.localURLOfCover = localURLOfCover;
        this.localURLOfPro = localURLOfPro;
        this.localURLOfRelative = localURLOfRelative;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getBELESSONID() {
        return BELESSONID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBELESSONID(String BELESSONID) {
        this.BELESSONID = BELESSONID;
    }

    public String getBETITLE() {
        return BETITLE;
    }

    public void setBETITLE(String BETITLE) {
        this.BETITLE = BETITLE;
    }

    public String getBEDESC() {
        return BEDESC;
    }

    public void setBEDESC(String BEDESC) {
        this.BEDESC = BEDESC;
    }

    public String getBEIMAGEURL() {
        return BEIMAGEURL;
    }

    public void setBEIMAGEURL(String BEIMAGEURL) {
        this.BEIMAGEURL = BEIMAGEURL;
    }

    public String getBECONTENTURL() {
        return BECONTENTURL;
    }

    public void setBECONTENTURL(String BECONTENTURL) {
        this.BECONTENTURL = BECONTENTURL;
    }

    public String getBESUBURL() {
        return BESUBURL;
    }

    public void setBESUBURL(String BESUBURL) {
        this.BESUBURL = BESUBURL;
    }

    public Double getBEDURATION() {
        return BEDURATION;
    }

    public void setBEDURATION(Double BEDURATION) {
        this.BEDURATION = BEDURATION;
    }

    public Double getBESTARTTIME() {
        return BESTARTTIME;
    }

    public void setBESTARTTIME(Double BESTARTTIME) {
        this.BESTARTTIME = BESTARTTIME;
    }

    public Integer getBELESSONS() {
        return BELESSONS;
    }

    public void setBELESSONS(Integer BELESSONS) {
        this.BELESSONS = BELESSONS;
    }

    public Double getBEDLPERCENT() {
        return BEDLPERCENT;
    }

    public void setBEDLPERCENT(Double BEDLPERCENT) {
        this.BEDLPERCENT = BEDLPERCENT;
    }

    public Boolean getBEDLSTATE() {
        return BEDLSTATE;
    }

    public void setBEDLSTATE(Boolean BEDLSTATE) {
        this.BEDLSTATE = BEDLSTATE;
    }

    public Boolean getBEOFFICIAL() {
        return BEOFFICIAL;
    }

    public void setBEOFFICIAL(Boolean BEOFFICIAL) {
        this.BEOFFICIAL = BEOFFICIAL;
    }

    public String getBEPROURL() {
        return BEPROURL;
    }

    public void setBEPROURL(String BEPROURL) {
        this.BEPROURL = BEPROURL;
    }

    public String getBELEVEL() {
        return BELEVEL;
    }

    public void setBELEVEL(String BELEVEL) {
        this.BELEVEL = BELEVEL;
    }

    public String getBECONTENTTYPE() {
        return BECONTENTTYPE;
    }

    public void setBECONTENTTYPE(String BECONTENTTYPE) {
        this.BECONTENTTYPE = BECONTENTTYPE;
    }

    public String getBEDOWNLOADTYPE() {
        return BEDOWNLOADTYPE;
    }

    public void setBEDOWNLOADTYPE(String BEDOWNLOADTYPE) {
        this.BEDOWNLOADTYPE = BEDOWNLOADTYPE;
    }

    public String getBETAG() {
        return BETAG;
    }

    public void setBETAG(String BETAG) {
        this.BETAG = BETAG;
    }

    public String getBEWEBURL() {
        return BEWEBURL;
    }

    public void setBEWEBURL(String BEWEBURL) {
        this.BEWEBURL = BEWEBURL;
    }

    public String getBEISBN() {
        return BEISBN;
    }

    public void setBEISBN(String BEISBN) {
        this.BEISBN = BEISBN;
    }

    public Integer getBECoinPrice() {
        return BECoinPrice;
    }

    public void setBECoinPrice(Integer BECoinPrice) {
        this.BECoinPrice = BECoinPrice;
    }

    public String getBERELATIVEURL() {
        return BERELATIVEURL;
    }

    public void setBERELATIVEURL(String BERELATIVEURL) {
        this.BERELATIVEURL = BERELATIVEURL;
    }

    public String getLocalURLOfContent() {
        return localURLOfContent;
    }

    public void setLocalURLOfContent(String localURLOfContent) {
        this.localURLOfContent = localURLOfContent;
    }

    public String getLocalURLOfSub() {
        return localURLOfSub;
    }

    public void setLocalURLOfSub(String localURLOfSub) {
        this.localURLOfSub = localURLOfSub;
    }

    public String getLocalURLOfCover() {
        return localURLOfCover;
    }

    public void setLocalURLOfCover(String localURLOfCover) {
        this.localURLOfCover = localURLOfCover;
    }

    public String getLocalURLOfPro() {
        return localURLOfPro;
    }

    public void setLocalURLOfPro(String localURLOfPro) {
        this.localURLOfPro = localURLOfPro;
    }

    public String getLocalURLOfRelative() {
        return localURLOfRelative;
    }

    public void setLocalURLOfRelative(String localURLOfRelative) {
        this.localURLOfRelative = localURLOfRelative;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
