package com.birdcopy.BirdCopyApp.Component.ActiveDAO;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table BE__STATISTIC.
 */
public class BE_STATISTIC {

    private Long id;
    /** Not-null value. */
    private String BEUSERID;
    private int BETOUCHCOUNT;
    private int BEMONEYCOUNT;
    private int BEGIFTCOUNT;
    private Integer BETIMES;
    private int BEQRCOUNT;
    /** Not-null value. */
    private String BETIMESTAMP;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public BE_STATISTIC() {
    }

    public BE_STATISTIC(Long id) {
        this.id = id;
    }

    public BE_STATISTIC(Long id, String BEUSERID, int BETOUCHCOUNT, int BEMONEYCOUNT, int BEGIFTCOUNT, Integer BETIMES, int BEQRCOUNT, String BETIMESTAMP) {
        this.id = id;
        this.BEUSERID = BEUSERID;
        this.BETOUCHCOUNT = BETOUCHCOUNT;
        this.BEMONEYCOUNT = BEMONEYCOUNT;
        this.BEGIFTCOUNT = BEGIFTCOUNT;
        this.BETIMES = BETIMES;
        this.BEQRCOUNT = BEQRCOUNT;
        this.BETIMESTAMP = BETIMESTAMP;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getBEUSERID() {
        return BEUSERID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBEUSERID(String BEUSERID) {
        this.BEUSERID = BEUSERID;
    }

    public int getBETOUCHCOUNT() {
        return BETOUCHCOUNT;
    }

    public void setBETOUCHCOUNT(int BETOUCHCOUNT) {
        this.BETOUCHCOUNT = BETOUCHCOUNT;
    }

    public int getBEMONEYCOUNT() {
        return BEMONEYCOUNT;
    }

    public void setBEMONEYCOUNT(int BEMONEYCOUNT) {
        this.BEMONEYCOUNT = BEMONEYCOUNT;
    }

    public int getBEGIFTCOUNT() {
        return BEGIFTCOUNT;
    }

    public void setBEGIFTCOUNT(int BEGIFTCOUNT) {
        this.BEGIFTCOUNT = BEGIFTCOUNT;
    }

    public Integer getBETIMES() {
        return BETIMES;
    }

    public void setBETIMES(Integer BETIMES) {
        this.BETIMES = BETIMES;
    }

    public int getBEQRCOUNT() {
        return BEQRCOUNT;
    }

    public void setBEQRCOUNT(int BEQRCOUNT) {
        this.BEQRCOUNT = BEQRCOUNT;
    }

    /** Not-null value. */
    public String getBETIMESTAMP() {
        return BETIMESTAMP;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBETIMESTAMP(String BETIMESTAMP) {
        this.BETIMESTAMP = BETIMESTAMP;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
