package com.birdcopy.BirdCopyApp.Component.ActiveDAO;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table BE__TOUCH__RECORD.
*/
public class BE_TOUCH_RECORDDao extends AbstractDao<BE_TOUCH_RECORD, Long> {

    public static final String TABLENAME = "BE__TOUCH__RECORD";

    /**
     * Properties of entity BE_TOUCH_RECORD.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property BEUSERID = new Property(1, String.class, "BEUSERID", false, "BEUSERID");
        public final static Property BELESSONID = new Property(2, String.class, "BELESSONID", false, "BELESSONID");
        public final static Property BETOUCHTIMES = new Property(3, Integer.class, "BETOUCHTIMES", false, "BETOUCHTIMES");
        public final static Property BETIMESTAMP = new Property(4, String.class, "BETIMESTAMP", false, "BETIMESTAMP");
    };


    public BE_TOUCH_RECORDDao(DaoConfig config) {
        super(config);
    }
    
    public BE_TOUCH_RECORDDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'BE__TOUCH__RECORD' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'BEUSERID' TEXT NOT NULL ," + // 1: BEUSERID
                "'BELESSONID' TEXT NOT NULL ," + // 2: BELESSONID
                "'BETOUCHTIMES' INTEGER," + // 3: BETOUCHTIMES
                "'BETIMESTAMP' TEXT);"); // 4: BETIMESTAMP
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'BE__TOUCH__RECORD'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, BE_TOUCH_RECORD entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getBEUSERID());
        stmt.bindString(3, entity.getBELESSONID());
 
        Integer BETOUCHTIMES = entity.getBETOUCHTIMES();
        if (BETOUCHTIMES != null) {
            stmt.bindLong(4, BETOUCHTIMES);
        }
 
        String BETIMESTAMP = entity.getBETIMESTAMP();
        if (BETIMESTAMP != null) {
            stmt.bindString(5, BETIMESTAMP);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public BE_TOUCH_RECORD readEntity(Cursor cursor, int offset) {
        BE_TOUCH_RECORD entity = new BE_TOUCH_RECORD( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // BEUSERID
            cursor.getString(offset + 2), // BELESSONID
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // BETOUCHTIMES
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // BETIMESTAMP
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, BE_TOUCH_RECORD entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setBEUSERID(cursor.getString(offset + 1));
        entity.setBELESSONID(cursor.getString(offset + 2));
        entity.setBETOUCHTIMES(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setBETIMESTAMP(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(BE_TOUCH_RECORD entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(BE_TOUCH_RECORD entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
