package com.birdcopy.BirdCopyApp.Component.ActiveDAO;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;

import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1000): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1000;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        BE_PUB_LESSONDao.createTable(db, ifNotExists);
        BE_LOCAl_LESSONDao.createTable(db, ifNotExists);
        BE_STATISTICDao.createTable(db, ifNotExists);
        BE_TOUCH_RECORDDao.createTable(db, ifNotExists);
        BE_TASK_WORDDao.createTable(db, ifNotExists);
        BE_RongUserDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        BE_PUB_LESSONDao.dropTable(db, ifExists);
        BE_LOCAl_LESSONDao.dropTable(db, ifExists);
        BE_STATISTICDao.dropTable(db, ifExists);
        BE_TOUCH_RECORDDao.dropTable(db, ifExists);
        BE_TASK_WORDDao.dropTable(db, ifExists);
        BE_RongUserDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(BE_PUB_LESSONDao.class);
        registerDaoClass(BE_LOCAl_LESSONDao.class);
        registerDaoClass(BE_STATISTICDao.class);
        registerDaoClass(BE_TOUCH_RECORDDao.class);
        registerDaoClass(BE_TASK_WORDDao.class);
        registerDaoClass(BE_RongUserDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
